# Generated by Django 4.0.2 on 2022-06-15 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playgame', '0002_topic_rom_host_message_rom_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rom',
            options={'ordering': ['-updates', '-created']},
        ),
        migrations.AddField(
            model_name='rom',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
