# Generated by Django 4.0.2 on 2022-06-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playgame', '0003_alter_rom_options_rom_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='coursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='playgame.coursename')),
            ],
        ),
    ]
