# Generated by Django 4.0.2 on 2022-06-23 14:49

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playgame', '0004_coursename_coursedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='link',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
